import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={styles.main}> */}
      <main className="flex flex-col justify-between items-center p-32 min-h-screen">
        {/* <div className={styles.description}> */}
        <div className="flex justify-between items-center text-sm max-w-6xl w-full z-2 font-mono">
          <p className="relative m-0 p-4 bg-[#14141480] border-2 border-[#6c6c6c4d] rounded-xl">
            Get started by editing&nbsp;
            {/* <code className={styles.code}>src/pages/index.js</code> */}
            <code className="font-bold font-mono">src/pages/index.js</code>
          </p>
          <div>
            <a
              className="flex justify-center items-center gap-2"
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                // className={styles.vercelLogo}
                className="invert"
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        {/* <div className={styles.center}> */}
        <div className="flex justify-center items-center">
          <Image
            //className={styles.logo}
            className="relative invert"
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        {/* <div className={styles.grid}> */}
        <div className="grid grid-cols-4 w-[1100px] max-w-full">
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            // className={styles.card}
            className="py-4 px-5 border-2 border-[#83868700] rounded-xl group"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={`font-semibold mb-3 ${inter.className}`}>
              Docs <span className="inline-block transition-transform group-hover:translate-x-1">-&gt;</span>
            </h2>
            <p className={`m-0 opacity-60 text-sm leading-[1.5] max-w-[30ch]${inter.className}`}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            // className={styles.card}
            className="py-4 px-5 group"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={`font-semibold mb-3 ${inter.className}`}>
              Learn <span className="inline-block transition-transform group-hover:translate-x-1">-&gt;</span>
            </h2>
            <p className={`m-0 opacity-60 text-sm leading-[1.5] max-w-[30ch]${inter.className}`}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            // className={styles.card}
            className="py-4 px-5 group"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={`font-semibold mb-3 ${inter.className}`}>
              Templates <span className="inline-block transition-transform group-hover:translate-x-1">-&gt;</span>
            </h2>
            <p className={`m-0 opacity-60 text-sm leading-[1.5] max-w-[30ch]${inter.className}`}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            // className={styles.card}
            className="py-4 px-5 group"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={`font-semibold mb-3 ${inter.className}`}>
              Deploy <span className="inline-block transition-transform group-hover:translate-x-1">-&gt;</span>
            </h2>
            <p className={`m-0 opacity-60 text-sm leading-[1.5] max-w-[30ch]${inter.className}`}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
